### ISSUE TITLE
Error: Formula `sleepwatcher` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by ahaolee** [dreamncn/SleepWithoutBluetoothAndWifi#1]
我在运行./install.sh后，在写入新的配置文件后，得到此错误
<img width="741" alt="image" src="https://user-images.githubusercontent.com/35681414/171993257-f3363e8e-92d1-4892-9900-489a3c7012d7.png">
系统版本：64bit Mac OS X 10.15.7 19H1922

**Comment by dreamncn** [comment]
先执行卸载脚本，卸载后再安装。

**Comment by ahaolee** [comment]
卸载后再安装就可以了，谢谢您！
