### ISSUE TITLE
系统升级后失效

### ISSUE THREAD

**Issue by zhangyf0206** [dreamncn/SleepWithoutBluetoothAndWifi#3]
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

**Comment by dreamncn** [comment]
执行`brew update`升级homebrew，或者直接重新安装homebrew：
```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
